const types = {
    GET_CONFIG: "GET_CONFIG",
    PROBLEM_GET_CONFIG: "PROBLEM_GET_CONFIG",
    UPDATE_IP_CONFIG: "UPDATE_IP_CONFIG",
    UPDATE_USER_CONFIG: "UPDATE_USER_CONFIG",
    UPDATE_PASS_CONFIG: "UPDATE_PASS_CONFIG",
    UPDATE_TOPIC_CONFIG: "UPDATE_TOPIC_CONFIG",
    UPDATE_STARTUP_CONFIG: "UPDATE_STARTUP_CONFIG",
}

export default types;

