const types = {
    GET_CONFIG: "GET_CONFIG",
    PROBLEM_GET_CONFIG: "PROBLEM_GET_CONFIG",
    UPDATE_IP_CONFIG: "UPDATE_IP_CONFIG",
    UPDATE_USER_CONFIG: "UPDATE_USER_CONFIG",
    UPDATE_PASS_CONFIG: "UPDATE_PASS_CONFIG",
    UPDATE_TOPIC_CONFIG: "UPDATE_TOPIC_CONFIG",
    UPDATE_STARTUP_CONFIG: "UPDATE_STARTUP_CONFIG",
    RESET_CONFIG: "RESET_CONFIG",
    SET_VIEW: "SET_VIEW",
    UPDATE_TEXT_TEXTAREA: "UPDATE_TEXT_TEXTAREA",
}

export default types;

